version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: baseDeDonnees
    volumes: 
      - dataEnLocal:/data/db
    env_file: 
      - ./env/mongo.env
  backend:
    build: ./backend
    container_name: NODE
    ports:
      - '80:80'
    volumes: 
      - logsEnLocal:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: REACT
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/:/app/
      - /app/node_modules
    env_file: 
      - ./env/react.env
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  dataEnLocal:
  logsEnLocal:
